---
- name: add repo containing latest ruby
  sudo: true
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: update apt repo
  sudo: true
  tags: upgrade
  apt: update_cache=yes

- name: install ruby packages
  sudo: true
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - ruby2.1
    - ruby2.1-dev
    - libxslt-dev # nokogiri requirement
    - libxml2-dev # nokogiri requirement
    - nodejs # several gems require a javscript runtime

- name: switch to use ruby2.1
  sudo: true
  command: update-alternatives --set ruby /usr/bin/ruby2.1

- name: switch to use gem2.1
  sudo: true
  command: update-alternatives --set gem /usr/bin/gem2.1

- name: upgrade apt packages
  sudo: true
  apt: upgrade=safe
  tags: upgrade
