---
- name: install postgres stack
  sudo: true
  apt: pkg={{ item }} state=latest install_recommends=no update_cache=yes
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: Create database user
  sudo_user: postgres
  postgresql_user: name={{database_username}} password={{database_password}} role_attr_flags=SUPERUSER

- name: create database(s)
  sudo: true
  sudo_user: postgres
  postgresql_db:
    db: "{{ item }}"
    owner: "{{ database_username }}"
    state: present
  with_items: 
    - '{{ databases }}'